In [1]:
# Dependencies
import requests
from pprint import pprint
import os
import pandas as pd
import datetime as dt
from dateutil.relativedelta import relativedelta as relativedelta

pd.options.mode.chained_assignment = None

In [2]:
def get_price(price_url, from_date, to_date):
    date_url = price_url\
        + "?from=" + str(from_date)\
        + "&to=" + str(to_date)\
        + "&serietype=line"
    date_json = requests.get(date_url).json()
    prices_list = date_json["historical"]
    prices_len = len(prices_list)
    date_close = prices_list[prices_len - 1]["close"]
    
    return date_close

In [3]:
nyse_csv = "companylist.csv"
nyse_df = pd.read_csv(nyse_csv)
nyse_df = nyse_df.drop(nyse_df.columns[[2, 3, 4, 6, 7, 8]], axis=1)
nyse_df = nyse_df.dropna()
len(nyse_df)
nyse_df.head(60)

   Symbol                                   Name                 Sector
0     DDD                 3D Systems Corporation             Technology
1     MMM                             3M Company            Health Care
2    WBAI                        500.com Limited      Consumer Services
3    WUBA                            58.com Inc.             Technology
4    EGHT                                8x8 Inc             Technology
5     AHC                  A.H. Belo Corporation      Consumer Services
6     AOS                  A.O Smith Corporation      Consumer Durables
7    ATEN                     A10 Networks, Inc.             Technology
8     AAC                     AAC Holdings, Inc.            Health Care
9     AIR                              AAR Corp.          Capital Goods
10    AAN                     Aaron&#39;s,  Inc.             Technology
11    ABB                                ABB Ltd      Consumer Durables
12    ABT                    Abbott Laboratories            Health Care
13   ABBV                            AbbVie Inc.            Health Care
14    ANF            Abercrombie & Fitch Company      Consumer Services
20    ABM            ABM Industries Incorporated                Finance
21    AKR                    Acadia Realty Trust      Consumer Services
22    ACN                          Accenture plc          Miscellaneous
23   ACCO                Acco Brands Corporation      Consumer Durables
24    ATV              Acorn International, Inc.      Consumer Services
25    ATU                    Actuant Corporation             Technology
26    AYI                   Acuity Brands, Inc.       Consumer Durables
27   GOLF                Acushnet Holdings Corp.  Consumer Non-Durables
30   AGRO                         Adecoagro S.A.  Consumer Non-Durables
31   ADNT                             Adient plc          Capital Goods
32    ADT                               ADT Inc.      Consumer Services
33   ATGE          Adtalem Global Education Inc.      Consumer Services
34    AAP                 Advance Auto Parts Inc      Consumer Services
35   ADSW       Advanced Disposal Services, Inc.       Public Utilities
36    WMS        Advanced Drainage Systems, Inc.          Capital Goods
37   ASIX                          AdvanSix Inc.       Basic Industries
39    ACM                                  AECOM      Consumer Services
40    AEB                               Aegon NV                Finance
41    AEG                               Aegon NV                Finance
42    AEH                               Aegon NV                Finance
43    AER                   Aercap Holdings N.V.             Technology
44   HIVE                Aerohive Networks, Inc.             Technology
45   AJRD     Aerojet Rocketdyne Holdings, Inc.           Capital Goods
46    AMG        Affiliated Managers Group, Inc.                Finance
47    MGR        Affiliated Managers Group, Inc.                Finance
48    AFL                     Aflac Incorporated                Finance
52   AGCO                       AGCO Corporation          Capital Goods
53      A             Agilent Technologies, Inc.          Capital Goods
54    AEM             Agnico Eagle Mines Limited       Basic Industries
55    ADC               Agree Realty Corporation      Consumer Services
56     AL                  Air Lease Corporation             Technology
58    APD       Air Products and Chemicals, Inc.       Basic Industries
59    AYR                      Aircastle Limited             Technology
60    AKS           AK Steel Holding Corporation       Basic Industries
62    ALG                      Alamo Group, Inc.          Capital Goods
63    AGI                       Alamos Gold Inc.       Basic Industries
64    ALK                 Alaska Air Group, Inc.         Transportation
65    AIN       Albany International Corporation       Basic Industries
66    ALB                  Albemarle Corporation       Basic Industries
67     AA                      Alcoa Corporation       Basic Industries
68    ALC                             Alcon Inc.            Health Care
69   ALEX              Alexander & Baldwin, Inc.      Consumer Services
70    ALX                  Alexander&#39;s, Inc.      Consumer Services
71    ARE  Alexandria Real Estate Equities, Inc.      Consumer Services
73    AQN      Algonquin Power & Utilities Corp.       Public Utilities

In [4]:
base_url = "https://financialmodelingprep.com/api/v3/historical-price-full/"
url_list = []

for index, row in nyse_df.iterrows():
    symbol_url = base_url + row["Symbol"]
    #print(symbol_url)
    url_list.append(symbol_url)
    
nyse_df["Symbol_URL"] = url_list
nyse_df.head()

,Symbol,Name,Sector,Symbol_URL
0,DDD,3D Systems Corporation,Technology,https://financialmodelingprep.com/api/v3/histo...
1,MMM,3M Company,Health Care,https://financialmodelingprep.com/api/v3/histo...
2,WBAI,500.com Limited,Consumer Services,https://financialmodelingprep.com/api/v3/histo...
3,WUBA,58.com Inc.,Technology,https://financialmodelingprep.com/api/v3/histo...
4,EGHT,8x8 Inc,Technology,https://financialmodelingprep.com/api/v3/histo...

In [5]:
dates_list = []

today = dt.date.today()
today_week = today - dt.timedelta(days=7)
year_1 = today - relativedelta(years=1)
year_1_week = year_1 - dt.timedelta(days=7)
year_3 = today - relativedelta(years=3)
year_3_week = year_3 - dt.timedelta(days=7)
year_5 = today - relativedelta(years=5)
year_5_week = year_5 - dt.timedelta(days=7)
year_10 = today - relativedelta(years=10)
year_10_week = year_10 - dt.timedelta(days=7)

dates_list.append([today_week, today])
dates_list.append([year_1_week, year_1])
dates_list.append([year_3_week, year_3])
dates_list.append([year_5_week, year_5])
dates_list.append([year_10_week, year_10])
dates_list

[[datetime.date(2019, 7, 31), datetime.date(2019, 8, 7)],
 [datetime.date(2018, 7, 31), datetime.date(2018, 8, 7)],
 [datetime.date(2016, 7, 31), datetime.date(2016, 8, 7)],
 [datetime.date(2014, 7, 31), datetime.date(2014, 8, 7)],
 [datetime.date(2009, 7, 31), datetime.date(2009, 8, 7)]]

In [6]:
test_df = nyse_df.head()
today_list = []
year_1_list = []

for index, row in test_df.iterrows():
    today_close = get_price(row["Symbol_URL"], dates_list[0][0], dates_list[0][1])
    today_list.append(today_close)
    year_1_close = get_price(row["Symbol_URL"], dates_list[1][0], dates_list[1][1])
    year_1_list.append(year_1_close)
    
print(today_list)
print(year_1_list)

test_df["Current"] = today_list
test_df["1 Year"] = year_1_list
test_df = test_df.drop(columns=["Symbol_URL"])

test_df

[8.14, 163.065, 10.585, 51.14, 24.035]
[13.57, 202.6294, 13.32, 67.51, 21.8]

  Symbol                    Name             Sector  Current    1 Year
0    DDD  3D Systems Corporation         Technology    8.140   13.5700
1    MMM              3M Company        Health Care  163.065  202.6294
2   WBAI         500.com Limited  Consumer Services   10.585   13.3200
3   WUBA             58.com Inc.         Technology   51.140   67.5100
4   EGHT                 8x8 Inc         Technology   24.035   21.8000

In [7]:
test_df["1 Year Change Percent"] = ((test_df["Current"] - test_df["1 Year"]) / test_df["Current"]) * 100
test_df

,Symbol,Name,Sector,Current,1 Year,1 Year Change Percent
0,DDD,3D Systems Corporation,Technology,8.140,13.5700,-66.707617
1,MMM,3M Company,Health Care,163.065,202.6294,-24.262963
2,WBAI,500.com Limited,Consumer Services,10.585,13.3200,-25.838451
3,WUBA,58.com Inc.,Technology,51.140,67.5100,-32.010168
4,EGHT,8x8 Inc,Technology,24.035,21.8000,9.298939

In [8]:
out_csv = "NYSE_Sector_Performance.csv"
test_df.to_csv(out_csv)